id: IFC51F76C
ocr_import_info:
  timestamp: '2023-07-10T12:49:23.556337+00:00'
  batch_id: batch-9db5
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-11 18:05:49.069731+00:00
last_modified: 2023-07-11 18:05:49.069743+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23700
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23700
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  languages:
  - bo
  author: གནས་མདོ་ཀརྨ་ཆགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.9856266576697241
  ocr_word_median_confidence_index: 0.99999994
bases:
  I2496:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2496
      total_pages: 609
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2496.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999994
      ocr_word_mean_confidence_index: 0.9856266576697241
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
